project:
  type: website
  render:
    - "*.qmd"

website:
  title: "Intro to Arrow in R"
  navbar:
    background: dark
    logo: "images/logo.png"
    right:
      - icon: github
        href: https://github.com/thisisnic/intro_to_arrow_workshop
        text: GitHub

    left:
      - href: index.qmd
        text: Home
      - text: Slides
        href: slides.qmd
        target: "_blank"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual
engine: knitr
execute:
  freeze: auto