project: 
  render:
    - slides.qmd
  output-dir: docs

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual
engine: knitr
execute:
  freeze: auto
  
